# Generated by Django 4.2.30 on 2026-09-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji for the sound, e.g. 🌧", max_length=10
                    ),
                ),
                ("audio_url", models.URLField(help_text="URL to the audio file")),
            ],
        ),
    ]
