# Generated by Django 4.2.30 on 2026-09-17 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0004_sound_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sound",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_sounds", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_sounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "css_class",
                    models.CharField(
                        help_text="e.g. 'midnight', 'forest', 'storm'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "background_color_hex",
                    models.CharField(
                        default="#0B1117",
                        help_text="Used for the dropdown option background",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
